spring:
  profiles:
    active:
      -  dog
      -  EN
      -  dev
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlJdbcurl

---
spring:
  profiles: prod
guru:
  username: ProdYmlUserName
  password: ProdYmlPassword
  jdbcurl: ProdYmlJdbcurl
